accounts_app/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . views import *
from .forms import LoginForm


app_name = 'accounts_app'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),

    path('dashboard/', dashboard, name='dashboard'),


    path('HRM/performance/', performance, name='performance'),
    path('HRM/add_performance/', add_performance, name='add_performance'),
    path('HRM/performance/<int:pk>/update/', update_performance, name='update_performance'),
    path('HRM/performance/<int:pk>/delete/', delete_performance, name='delete_performance'),


    path('HRM/payroll/', payroll, name='payroll'),
    path('HRM/add_payroll/', add_payroll, name='add_payroll'),
    path('HRM/payroll/<int:pk>/update/', update_payroll, name='update_payroll'),
    path('HRM/payroll/<int:pk>/delete/', delete_payroll, name='delete_payroll'),


    path('HRM/notice/', notice, name='notice'),
    path('HRM/add_notice/', add_notice, name='add_notice'),
    path('HRM/notice/<int:pk>/update/', update_notice, name='update_notice'),
    path('HRM/notice/<int:pk>/delete/', delete_notice, name='delete_notice'),


    path('HRM/attendence/', attendence, name='attendence'),
    path('HRM/add_attendence/', add_attendence, name='add_attendence'),
    path('HRM/attendence/<int:pk>/update/', update_attendence, name='update_attendence'),
    path('HRM/attendence/<int:pk>/delete/', delete_attendence, name='delete_attendence'),





    path('addadjustement/', addadjustement, name='addadjustement'),
    path('adjustmentlist/', adjustmentlist, name='adjustmentlist'),

    path('brands/', brands, name='brands'),
    path('products/', products, name='products'),
    path('categories/', categories, name='categories'),
    path('sub-categories/', sub_categories, name='sub-categories'),
    path('biller/', biller, name='biller'),
    path('addbiller/', addbiller, name='addbiller'),
    path('addsuppliers/', addsuppliers, name='addsuppliers'),
    path('suppliers/', suppliers, name='suppliers'),
    path('saleslist/', saleslist, name='saleslist'),
    path('addsales/', addsales, name='addsales'),
    path('addpurchase/', addpurchase, name='addpurchase'),
    path('purchaselist/', purchaselist, name='purchaselist'),

    path('telecalling/', telecalling, name='telecalling'),
    path('conversations/', conversations, name='conversations'),


    path('appointments/', appointments, name='appointments'),
    path('appointments/create/', create_appointment, name='create_appointment'),
    path('appointments/<int:pk>/update/', update_appointment, name='update_appointment'),
    path('appointments/<int:pk>/delete/', delete_appointment, name='delete_appointment'),


    path('salestracker/', salestracker, name='salestracker'),
    path('salestracker/create/', create_salestracker, name='create_salestracker'),
    path('salestracker/<int:pk>/update/', update_salestracker, name='update_salestracker'),
    path('salestracker/<int:pk>/delete/', delete_salestracker, name='delete_salestracker'),

    
    path('leads/', leads, name='leads'),
    path('leads/create/', add_lead, name='add_lead'),
    path('leads/<int:pk>/update/', update_lead, name='update_lead'),
    path('leads/<int:pk>/delete/', delete_lead, name='delete_lead'),
    

    path('taskmanager/', taskmanager, name='taskmanager'),
    path('taskmanager/create/', add_taskmanager, name='add_taskmanager'),
    path('taskmanager/<int:pk>/update/', update_taskmanager, name='update_taskmanager'),
    path('taskmanager/<int:pk>/delete/', delete_taskmanager, name='delete_taskmanager'),


    path('properties/', properties, name='properties'),
    path('propertymanager/', propertymanager, name='propertymanager'),
    path('customers/', customers, name='customers'),
    path('calendar/', calendar, name='calendar'),


    path('settings/general_setting/', general_setting, name='general_setting'),
    path('settings/email_setting/', email_setting, name='email_setting'),
    path('settings/sms_setting/', sms_setting, name='sms_setting'),
    path('settings/currency_setting/', currency_setting, name='currency_setting'),
    path('settings/tax_setting/', tax_setting, name='tax_setting'),
    path('settings/location_setting/', location_setting, name='location_setting'),
    path('settings/lead_status_setting/', lead_status_setting, name='lead_status_setting'),
    path('settings/lead_source_setting/', lead_source_setting, name='lead_source_setting'),
    path('settings/notification_setting/', notification_setting, name='notification_setting'),
    path('settings/call_status_setting/', call_status_setting, name='call_status_setting'),
    path('settings/custom_field_setting/', custom_field_setting, name='custom_field_setting'),


    path('usermanagement/employees/create/', add_employees, name='add_employees'),
    path('usermanagement/employees/', employees, name='employees'),
    path('usermanagement/employees/<int:pk>/update/', update_employees, name='update_employees'),
    path('usermanagement/employees/<int:pk>/delete/', delete_employees, name='delete_employees'),

]

admin_app/urls.py
from django.urls import path
from . views import *

app_name = 'admin_app'


urlpatterns = [
    path('', base, name='base'),

    path('about/', about, name='about'),
    path('plans/', plans, name='plans'),

    

]

super_user/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('admin_app.urls')),
    path('',include('accounts_app.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import SignupForm, LoginForm
from django.views.decorators.csrf import csrf_exempt
from .forms import *
from . models import *
from django.contrib import messages



@csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        print(form)
        if form.is_valid():
            user = form.save()
            print(user)
            authenticate(username=user.username, password=user.password)

            if user is not None:
                login(request, user)

                return redirect('/')
        else:
            messages.error(request, 'Invalid username or password')
    else:
        form = SignupForm()

    return render(request, 'accounts_app/user_signup.html', {
        'form': form
    })


def user_login(request):
    if request.method == 'POST':
        print(request.POST)
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('accounts_app:dashboard')
        else:
            messages.error(request, 'Invalid username or password')
    
    form = LoginForm()
    return render(request, 'accounts_app/user_login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return redirect('/')

@login_required
def dashboard(request):
    return render(request, 'accounts_app/dashboard/dashboard.html')

@login_required
def performance(request):
    performance = Performance.objects.all()
    return render(request, 'accounts_app/HRM/performance.html', {'performance': performance})

@login_required
def add_performance(request):
    if request.method == 'POST':
        form = PerformanceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:performance')
    else:
        form = PerformanceForm()
    return render(request, 'accounts_app/HRM/add_performance.html', {'form': form})

@login_required
def update_performance(request, pk):
    if request.method == 'POST':
        performance = get_object_or_404(Performance, pk=pk)
        form = PerformanceForm(request.POST, instance=performance)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:performance')
    else:
        performance = get_object_or_404(Performance, pk=pk)
        form = PerformanceForm(instance=performance)
    return render(request, 'accounts_app/HRM/update_performance.html', {'form': form})

@login_required
def delete_performance(request, pk):
    if request.method == 'POST':
        performance = get_object_or_404(Performance, pk=pk)
        performance.delete()
        return redirect('accounts_app:performance')
    return render(request, 'accounts_app/HRM/delete_performance.html', {'performance': performance})

@login_required
def payroll(request):
    payroll = Payroll.objects.all()
    return render(request, 'accounts_app/HRM/payroll.html', {'payroll': payroll})

@login_required
def add_payroll(request):
    if request.method == 'POST':
        form = PayrollForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:payroll')
    else:
        form = PayrollForm()
    return render(request, 'accounts_app/HRM/add_payroll.html', {'form': form})

@login_required
def update_payroll(request, pk):
    payroll = get_object_or_404(Payroll, pk=pk)
    if request.method == 'POST':
        form = PayrollForm(request.POST, instance=payroll)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:payroll')
    else:
        form = PayrollForm(instance=payroll)
    return render(request, 'accounts_app/HRM/update_payroll.html', {'form': form})

@login_required
def delete_payroll(request, pk):
    if request.method == 'POST':
        payroll = get_object_or_404(Payroll, pk=pk)
        payroll.delete()
        return redirect('accounts_app:payroll')
    return render(request, 'accounts_app/HRM/payroll.html', {'payroll': payroll})


@login_required
def notice(request):
    notice = Notice.objects.all()
    return render(request, 'accounts_app/HRM/notice.html', {'notice': notice})


@login_required
def add_notice(request):
    if request.method == 'POST':
        form = NoticeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:notice')
    else:
        form = NoticeForm()
    return render(request, 'accounts_app/HRM/add_notice.html', {'form': form})

@login_required
def update_notice(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    if request.method == 'POST':
        form = NoticeForm(request.POST, instance=notice)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:notice')
    else:
        form = NoticeForm(instance=notice)
    return render(request, 'accounts_app/HRM/update_notice.html', {'form': form})


@login_required
def delete_notice(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    if request.method == 'POST':
        notice.delete()
        return redirect('accounts_app:notice')
    return render(request, 'accounts_app/HRM/delete_notice.html', {'notice': notice})




@login_required
def attendence(request):
    attendence = Attendence.objects.all()
    return render(request, 'accounts_app/HRM/attendence.html', {'attendence': attendence})

@login_required
def add_attendence(request):
    if request.method == 'POST':
        form = AttendenceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:attendence')
    else:
        form = AttendenceForm()
    return render(request, 'accounts_app/HRM/add_attendence.html', {'form': form})

@login_required
def update_attendence(request, pk):
    attendence = get_object_or_404(Attendence, pk=pk)
    if request.method == 'POST':
        form = AttendenceForm(request.POST, instance=attendence)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:attendence')
    else:
        form = AttendenceForm(instance=attendence)
    return render(request, 'accounts_app/HRM/update_attendence.html', {'form': form})





@login_required
def delete_attendence(request, pk):
    attendence = get_object_or_404(Attendence, pk=pk)
    if request.method == 'POST':
        attendence.delete()
        return redirect('accounts_app:attendence')
    return render(request, 'accounts_app/HRM/delete_attendence.html', {'attendence': attendence})



@login_required
def addadjustement(request):
    return render(request, 'accounts_app/adjustments/addadjustement.html')

@login_required
def adjustmentlist(request):
    return render(request, 'accounts_app/adjustments/adjustmentlist.html')

@login_required
def brands(request):
    return render(request, 'accounts_app/brands.html')

@login_required
def products(request):
    return render(request, 'accounts_app/products.html')

@login_required
def categories(request):
    return render(request, 'accounts_app/categories.html')

@login_required
def sub_categories(request):
    return render(request, 'accounts_app/sub-categories.html')

@login_required
def biller(request):
    return render(request, 'accounts_app/biller.html')

@login_required
def addsuppliers(request):
    return render(request, 'accounts_app/addsuppliers.html')

@login_required
def suppliers(request):
    return render(request, 'accounts_app/suppliers.html')

@login_required
def saleslist(request):
    return render(request, 'accounts_app/saleslist.html')

@login_required
def addsales(request):
    return render(request, 'accounts_app/addsales.html')

@login_required
def addpurchase(request):
    return render(request, 'accounts_app/addpurchase.html')

@login_required
def purchaselist(request):
    return render(request, 'accounts_app/purchaselist.html')

@login_required
def telecalling(request):
    return render(request, 'accounts_app/telecalling.html')

@login_required
def conversations(request):
    return render(request, 'accounts_app/conversations.html')

@login_required
def appointments(request):
    appointments = Appointment.objects.all()  
    return render(request, 'accounts_app/appointments/appointments.html', {'appointments': appointments})

@login_required
def create_appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:appointments')
    else:
        form = AppointmentForm()
    return render(request, 'accounts_app/appointments/create_appointment.html', {'form': form})


@login_required
def update_appointment(request, pk):
    appointment = get_object_or_404(Appointment, pk=pk)
    if request.method == 'POST':
        form = AppointmentForm(request.POST, instance=appointment)
        if form.is_valid():
            form.save()
            return redirect('accounts_app:appointments')
    else:
        form = AppointmentForm(instance=appointment)
    return render(request, 'accounts_app/appointments/update_appointment.html', {'form': form})


@login_required
def delete_appointment(request, pk):
    appointment = get_object_or_404(Appointment, pk=pk)
    if request.method == 'POST':
        appointment.delete()
        return redirect('accounts_app:appointments')
    return render(request, 'accounts_app/appointments/delete_appointment.html', {'appointment': appointment})


@login_required
def salestracker(request):
    salestracker = SalesTracker.objects.all()
    return render(request, 'accounts_app/salestracker/salestracker.html', {'salestracker': salestracker})

@login_required

templates/accounts_app/taskmanager/add_taskmanager.html
{% extends "base.html" %}

{% block title %}Add Task{% endblock %}

{% block content %}
<h1>Add Task</h1>
<style>
    /* Resetting default margins and paddings */
body, h1, form {
    margin: 0;
    padding: 0;
}

/* Setting a nice background and font */
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background-color: #f4f4f4;
}

/* Giving the form a bit of padding and a background */
form {
    padding: 20px;
    background-color: #fff;
    border-radius: 10px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    width: 70%;
    margin: 0 auto; /* Centering the form horizontally */
}

/* Styling the form title */
h1 {
    color: #333;
    margin-bottom: 20px;
}

/* Styling form inputs and labels */
label {
    margin-bottom: 10px;
    font-weight: bold;
    display: block;
}

/* Styling form fields */
.form-row {
    margin-bottom: 20px;
    text-align: center; /* Center the form groups */
}

.form-group {
    display: inline-block;
    width: calc(30% - 20px); /* Adjusting for margins */
    margin-right: 20px;
}

/* Styling form elements */
input[type="text"],
select,
textarea {
    width: 50%;
    padding: 5px;
    margin: 5px 0;
    border: 3px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
    transition: border-color 0.9s;
}

/* Styling focused form elements */
input[type="text"]:focus,
select:focus,
textarea:focus {
    border-color: #4CAF50;
    outline: none;
}

/* Styling the submit button */
button[type="submit"] {
    padding: 10px 20px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s;
}

button[type="submit"]:hover {
    background-color: #45a049;
}

</style>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

templates/accounts_app/taskmanager/delete_taskmanager.html
{% extends "base.html" %}

{% block title %}Delete Task Manager{% endblock %}

{% block content %}
<h1>Delete Task Manager</h1>

<p>Are you sure you want to delete the Task Manager for {{ tasks.lead_id }} (Name: {{ tasks.name }})?</p>

<form action="{% url 'delete_taskmanager' tasks.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>
{% endblock %}

templates/accounts_app/taskmanager/taskmanager.html
{% extends "base.html" %}

{% block title %}Admin{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Manager</title>


    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            padding: 20px;
        }
        h1 {
            color: #333;
        }
        .card-container {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .card {
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            width: calc(20% - 20px);
            box-sizing: border-box;
        }
        .card h2 {
            color: #333;
            margin-top: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #e6f7ff; /* Blue color */
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #3399ff; /* Dark blue color for header */
            color: #fff;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2; /* Light gray color for even rows */
        }
        tr:hover {
            background-color: #cceeff; /* Light blue color on hover */
        }
        .search-container {
            margin-bottom: 20px;
        }
        .search-container input[type=text] {
            padding: 10px;
            margin-right: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        .download-button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .download-button:hover {
            background-color: #45a049;
        }
        .header-actions {
            display: flex;
            justify-content: flex-end;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <h1>Task Manager</h1>

    <div class="header-actions">
        <button class="download-button" onclick="exportToExcel()">Download as Excel</button>
    </div>

    <div>
        <a href="{% url 'accounts_app:add_taskmanager' %}" class="create-button">Add Tasks</a>
    </div>

    <div class="search-container">
        <input type="text" id="search-input" placeholder="Search...">
        <button onclick="search()">Search</button>
    </div>

    <div class="card-container">
        <div class="card">
            <h2>Card 1</h2>
            <p>Content for card 1</p>
        </div>
        <div class="card">
            <h2>Card 2</h2>
            <p>Content for card 2</p>
        </div>
        <div class="card">
            <h2>Card 3</h2>
            <p>Content for card 3</p>
        </div>
        <div class="card">
            <h2>Card 4</h2>
            <p>Content for card 4</p>
        </div>
        <div class="card">
            <h2>Card 5</h2>
            <p>Content for card 5</p>
        </div>
        <div class="card">
            <h2>Card 6</h2>
            <p>Content for card 6</p>
        </div>
    </div>

    <table border="1">
        <thead>
            <tr>
                <th>S.No</th>                
                <th>Name</th>
                <th>Mobile</th>
                <th>Date</th>
                <th>Project Name</th>
                <th>Project Details</th>
                <th>Project Type</th>
                <th>Status</th>
                <th>Assigned To</th>
                <th>Lead Circle</th>
                <th>Source</th>  
                <th>Lead ID</th>
                <th>Actions</th>              
            </tr>
        </thead>
        <tbody>
            {% for tasks in taskmanager %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ tasks.name }}</td>
                <td>{{ tasks.mobile }}</td>
                <td>{{ tasks.date }}</td>
                <td>{{ tasks.Project_Name }}</td>
                <td>{{ tasks.Project_Details }}</td>
                <td>{{ tasks.Project_Type }}</td>
                <td>{{ tasks.status }}</td>
                <td>{{ tasks.assigned_to }}</td>
                <td>{{ tasks.lead_circle }}</td>
                <td>{{ tasks.source }}</td>
                <td>{{ tasks.lead_id }}</td>
                <td>
                    <a href="{% url 'accounts_app:update_taskmanager' tasks.pk %}">Edit</a>
                    <form action="{% url 'accounts_app:delete_taskmanager' tasks.pk %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this task manager?')">
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        function search() {
            // Write your search functionality here
        }

        function exportToExcel() {
            // Write code to export table data to Excel format
        }
    </script>
</body>
</html>
{% endblock %}

templates/accounts_app/taskmanager/update_taskmanager.html
{% extends "base.html" %}

{% block title %}Update Task Manager{% endblock %}

{% block content %}
<h1>Update Task Manager</h1>
<style>

    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        padding: 20px;
        margin: 0;
    }
    
    h1 {
        color: #333;
    }
    
    .header-actions {
        margin-bottom: 20px;
    }
    
    .header-actions a,
    .download-button {
        display: inline-block;
        padding: 10px 20px;
        margin-right: 10px;
        background-color: #4CAF50;
        color: white;
        text-decoration: none;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    
    .header-actions a:hover,
    .download-button:hover {
        background-color: #45a049;
    }
    
    .search-container {
        margin-bottom: 20px;
    }
    
    .search-container input[type="text"] {
        padding: 10px;
        margin-right: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }
    
    th, td {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }
    
    th {
        background-color: #3399ff;
        color: #fff;
    }
    
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    
    tr:hover {
        background-color: #cceeff;
    }
    
    form {
        margin-top: 20px;
    }
    
    form input[type="text"],
    form select,
    form textarea {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }
    
    form button[type="submit"] {
        padding: 10px 20px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    
    form button[type="submit"]:hover {
        background-color: #45a049;
    }
    
</style>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>
{% endblock %}